services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - wwebjs_auth:/app/.wwebjs_auth
      - wwebjs_cache:/app/.wwebjs_cache
    command: npm run dev
    restart: always

volumes:
  node_modules:
  wwebjs_auth:
  wwebjs_cache: